
java_library(
    name = "zoltar-tests",
    visibility = ["//visibility:public"],
    exports = [
        "//zoltar-tests/src/main/java/com/spotify/zoltar",
        "//zoltar-tests/src/main/scala/com/spotify/zoltar"
    ],
)