package(default_visibility = ["//visibility:public"])

java_library(
    name = "featran",
    srcs = glob(["**/*.java"]),
    deps = [
        "//3rdparty/jvm/com/spotify:featran_java_2_11",
        "//3rdparty/jvm/com/spotify:featran_core_2_11",
        "//3rdparty/jvm/com/spotify:featran_xgboost_2_11",
        "//3rdparty/jvm/org/tensorflow:proto",
        "//3rdparty/jvm/ml/dmlc:xgboost4j",
        "//zoltar-core"
        ],
)