#java_library(
#    name = "resources",
#    resources = glob(["**/*"]),
#    visibility = ["//zoltar-tests:__subpackages__"],
#)

filegroup(
    name = "resources",
    testonly = 1,
    srcs = glob(["**/*"]),
    visibility = ["//zoltar-tests:__subpackages__"],
)