
java_test(
    name = "VectorTest",
    size = "small",
    srcs = ["VectorTest.java"],
    runtime_deps = ["//zoltar-tests/src/test"],
    deps = [
        "//3rdparty/jvm/org/junit:junit",
        "//zoltar-core",
    ],
)