package(default_visibility = ["//visibility:public"])

java_library(
    name = "zoltar",
    srcs = glob(["**/*.java"]),
    deps = [
        "//3rdparty/jvm/com/google/auto/value:auto_value",
        "//3rdparty/jvm/com/google/guava:guava",
        "//3rdparty/jvm/com/google/cloud:google_cloud_nio",
        "//3rdparty/jvm/com/google/protobuf:protobuf_java_util"
        ],
)