package(default_visibility = ["//visibility:public"])

java_library(
    name = "zoltar",
    srcs = glob(["*.java"]),
    deps = [
        "//zoltar-core",
        "//zoltar-metrics",
        "//zoltar-tensorflow",
        "//zoltar-xgboost",
        "//zoltar-featran",
        "//zoltar-mlengine",
        "//3rdparty/jvm/org/tensorflow:proto",
        "//3rdparty/jvm/org/tensorflow:libtensorflow",
        "//3rdparty/jvm/com/google/code/findbugs:jsr305"
        ],
)